CREATE TABLE IF NOT EXISTS LLM_CustomPrompts (
    ID TEXT NOT NULL PRIMARY KEY,
    CreatorID TEXT NOT NULL,
    Name TEXT NOT NULL,
    Description TEXT NOT NULL DEFAULT '',
    Template TEXT NOT NULL DEFAULT '',
    IsShared BOOLEAN NOT NULL DEFAULT FALSE,
    CreatedAt BIGINT NOT NULL DEFAULT 0,
    UpdatedAt BIGINT NOT NULL DEFAULT 0,
    DeletedAt BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS LLM_CustomPromptPins (
    UserID TEXT NOT NULL,
    PromptID TEXT NOT NULL,
    PRIMARY KEY (UserID, PromptID)
);
